#!/bin/bash
# install-on-vps.sh — install hundler-xray-agent on a freshly-provisioned
# (or existing) Xray node. Replaces /opt/xray-sync.sh + /opt/xray-webhook.py.
#
# Idempotent — re-run after binary update is safe.
#
# Usage (local machine):
#   scp dist/xray-sync hundler-xray-agent.service install-on-vps.sh root@<vps>:/tmp/
#   ssh root@<vps> 'bash /tmp/install-on-vps.sh \
#                     --sync-token "<from-DB.servers.sync_token>" \
#                     --server-host "<DB.servers.host>" \
#                     --api-url "https://hundlervpn.xyz/api/xray/clients"'
#
# Rollback:
#   bash /tmp/install-on-vps.sh --uninstall
#   This restores the legacy bash + python webhook trio.

set -euo pipefail

# ── Args ─────────────────────────────────────────────────────────────────
SYNC_TOKEN=""
SERVER_HOST=""
API_URL="https://hundlervpn.xyz/api/xray/clients"
INBOUND_TAG="vless-in"
GRPC_TARGET="127.0.0.1:10085"
WEBHOOK_PORT="9999"
PULL_INTERVAL_MS="300000"
UNINSTALL=false

while [ $# -gt 0 ]; do
  case "$1" in
    --sync-token)      SYNC_TOKEN="$2"; shift 2 ;;
    --server-host)     SERVER_HOST="$2"; shift 2 ;;
    --api-url)         API_URL="$2"; shift 2 ;;
    --inbound-tag)     INBOUND_TAG="$2"; shift 2 ;;
    --grpc-target)     GRPC_TARGET="$2"; shift 2 ;;
    --webhook-port)    WEBHOOK_PORT="$2"; shift 2 ;;
    --pull-interval-ms) PULL_INTERVAL_MS="$2"; shift 2 ;;
    --uninstall)       UNINSTALL=true; shift ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

log() { echo "[install-on-vps] $*"; }

# ── Uninstall path ──────────────────────────────────────────────────────
if [ "$UNINSTALL" = "true" ]; then
  log "Uninstalling hundler-xray-agent…"
  systemctl stop hundler-xray-agent.service 2>/dev/null || true
  systemctl disable hundler-xray-agent.service 2>/dev/null || true
  rm -f /etc/systemd/system/hundler-xray-agent.service
  rm -f /opt/hundler-xray-agent
  rm -rf /opt/proto
  rm -rf /etc/hundler-xray-agent

  # Restore legacy webhook + cron (если они выключены при install).
  if [ -f /etc/systemd/system/xray-webhook.service ]; then
    systemctl enable --now xray-webhook.service 2>/dev/null || true
  fi
  # Restore legacy cron line.
  if ! crontab -l 2>/dev/null | grep -q '/opt/xray-sync.sh'; then
    {
      crontab -l 2>/dev/null || true
      echo "*/5 * * * * /opt/xray-sync.sh >> /var/log/xray-sync.log 2>&1"
    } | crontab -
  fi

  systemctl daemon-reload
  log "Uninstall complete. Legacy bash sync re-enabled."
  exit 0
fi

# ── Pre-flight ──────────────────────────────────────────────────────────
if [ -z "$SYNC_TOKEN" ]; then
  echo "ERROR: --sync-token is required" >&2
  exit 1
fi

if [ ! -f /tmp/xray-sync ] && [ ! -f /opt/hundler-xray-agent.new ]; then
  echo "ERROR: binary not found at /tmp/xray-sync (scp it first)" >&2
  exit 1
fi

if [ ! -d /tmp/proto ]; then
  echo "ERROR: proto/ directory not found at /tmp/proto (scp -r agent/proto root@<vps>:/tmp/)" >&2
  echo "       bun --compile НЕ embed'ит .proto, они нужны рядом с бинарём." >&2
  exit 1
fi

if ! command -v xray >/dev/null 2>&1 && [ ! -x /usr/local/bin/xray ]; then
  echo "ERROR: /usr/local/bin/xray not found — это не Xray-нода?" >&2
  exit 1
fi

# Проверяем что в config.json есть API inbound на 127.0.0.1:10085.
# Если нет — добавляем (см. add-api-inbound.sh — отдельный скрипт).
if ! grep -q 'HandlerService' /usr/local/etc/xray/config.json 2>/dev/null; then
  echo "ERROR: API inbound НЕ настроен в /usr/local/etc/xray/config.json" >&2
  echo "       Запусти agent/deploy/add-api-inbound.sh сначала." >&2
  exit 1
fi

# ── Install binary ──────────────────────────────────────────────────────
if [ -f /tmp/xray-sync ]; then
  log "Installing /opt/hundler-xray-agent…"
  install -m 0755 /tmp/xray-sync /opt/hundler-xray-agent
elif [ -f /opt/hundler-xray-agent.new ]; then
  # Поддержка обновления через rsync /opt/hundler-xray-agent.new
  log "Activating staged binary /opt/hundler-xray-agent.new…"
  mv /opt/hundler-xray-agent.new /opt/hundler-xray-agent
  chmod 0755 /opt/hundler-xray-agent
fi

# Копируем proto/ рядом с бинарём — agent резолвит их через process.execPath.
log "Installing /opt/proto/…"
rm -rf /opt/proto
cp -r /tmp/proto /opt/proto
find /opt/proto -type d -exec chmod 0755 {} \;
find /opt/proto -type f -exec chmod 0644 {} \;

# ── Env file ────────────────────────────────────────────────────────────
log "Writing /etc/hundler-xray-agent/env…"
install -d -m 0700 /etc/hundler-xray-agent
cat > /etc/hundler-xray-agent/env <<EOF
# Generated by install-on-vps.sh on $(date -Iseconds)
# Edit by hand if you need to change params, then:
#   systemctl restart hundler-xray-agent
SYNC_TOKEN=${SYNC_TOKEN}
WEBHOOK_TOKEN=${SYNC_TOKEN}
API_URL=${API_URL}
INBOUND_TAG=${INBOUND_TAG}
GRPC_TARGET=${GRPC_TARGET}
WEBHOOK_PORT=${WEBHOOK_PORT}
PULL_INTERVAL_MS=${PULL_INTERVAL_MS}
SERVER_HOST=${SERVER_HOST}
XRAY_CONFIG_PATH=/usr/local/etc/xray/config.json
SANITY_FLOOR=1
LOG_LEVEL=info
EOF
chmod 0600 /etc/hundler-xray-agent/env

# ── systemd unit ────────────────────────────────────────────────────────
log "Installing /etc/systemd/system/hundler-xray-agent.service…"
install -m 0644 /tmp/hundler-xray-agent.service /etc/systemd/system/

systemctl daemon-reload

# ── Disable legacy syncing ──────────────────────────────────────────────
# Не удаляем /opt/xray-sync.sh + /opt/xray-webhook.py файлы — оставляем
# как rollback option (см. --uninstall выше). Только отключаем cron+systemd.
log "Disabling legacy bash sync (cron + xray-webhook.service)…"
systemctl stop xray-webhook.service 2>/dev/null || true
systemctl disable xray-webhook.service 2>/dev/null || true

# Remove cron line(s) for /opt/xray-sync.sh
if crontab -l 2>/dev/null | grep -q '/opt/xray-sync.sh'; then
  log "Removing /opt/xray-sync.sh cron line…"
  crontab -l 2>/dev/null | grep -v '/opt/xray-sync.sh' | crontab -
fi

# ── Start agent ─────────────────────────────────────────────────────────
log "Starting hundler-xray-agent…"
systemctl enable --now hundler-xray-agent.service

# ── Smoke test ──────────────────────────────────────────────────────────
# bun-compiled binary boot ~ 1.5-2 s on a fresh VPS where TLS root certs
# и DNS cache холодные; добавим retry loop (5 попыток × 2 секунды) чтобы
# не падать на slow VPS (Hostman Novosibirsk показал >3 s в холодном
# state). Если за 10 секунд /health не отвечает — реальная проблема,
# смотрим journalctl.
log "Probing /health…"
HEALTH_OK=false
for i in 1 2 3 4 5; do
  sleep 2
  if curl -fsS "http://127.0.0.1:${WEBHOOK_PORT}/health" 2>/dev/null | grep -q '"ok":true'; then
    HEALTH_OK=true
    break
  fi
done
if $HEALTH_OK; then
  log "✅ Agent healthy."
else
  echo "ERROR: /health probe failed after 10s. Check journalctl -u hundler-xray-agent" >&2
  exit 1
fi

log "Done. Tail logs with: journalctl -u hundler-xray-agent -f"
